routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClaimController;
use App\Http\Controllers\RealtyController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ReadingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::resource('client', ClientController::class);

    Route::resource('claim', ClaimController::class);

    Route::resource('realty', RealtyController::class);

    Route::resource('reading', ReadingController::class);
});

require __DIR__.'/auth.php';

app/Models/Realty.php
<?php

namespace App\Models;

use App\Dictionary\RealtyType;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Realty extends Model
{
    use HasFactory;

    /**
     * @inheritdoc
     */
    protected $table = 'realty';

    /**
     * @inheritdoc
     */
    protected $fillable = [
        'account', 'type', 'street', 'house', 'flat', 'entrance', 'floor', 'square'
    ];

    /**
     * @return string
     */
    public function getFullNameAttribute(): string
    {
        return $this->street . ', д. ' . $this->house . ', кв. ' . $this->flat;
    }

    /**
     * @return string
     */
    public function getTypeNameAttribute(): string
    {
        return RealtyType::TYPES[$this->type];
    }

    /**
     * @return HasOne
     */
    public function client(): HasOne
    {
        return $this->hasOne(Client::class);
    }

    /**
     * @return HasMany
     */
    public function readings(): HasMany
    {
        return $this->hasMany(Reading::class);
    }
}

app/Http/Controllers/RealtyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Realty;
use Illuminate\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use App\Http\Requests\StoreRealtyRequest;
use App\Http\Requests\UpdateRealtyRequest;

class RealtyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index()
    {
        return view('realty.index', [
            'realtys' => Realty::query()->paginate()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create()
    {
        return view('realty.create', ['realty' => new Realty()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreRealtyRequest $request
     * @return RedirectResponse
     */
    public function store(StoreRealtyRequest $request)
    {
        Realty::query()->create($request->validated());

        return redirect()->route('realty.index')->with('success', 'Объект Добавлен!');
    }

    /**
     * Display the specified resource.
     *
     * @param Realty $realty
     * @return View
     */
    public function show(Realty $realty)
    {
        return view('realty.show', ['realty' => $realty]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Realty $realty
     * @return View
     */
    public function edit(Realty $realty)
    {
        return view('realty.edit', ['realty' => $realty]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateRealtyRequest $request
     * @param Realty              $realty
     * @return RedirectResponse
     */
    public function update(UpdateRealtyRequest $request, Realty $realty)
    {
        $realty->update($request->validated());

        return redirect()->route('realty.index')->with('success', 'Объект Обновлен!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Realty $realty
     * @return JsonResponse
     */
    public function destroy(Realty $realty)
    {
        $realty->delete();

        return response()->json(['status' => 'success', 'message' => 'Объект Удален!']);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\View;
use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/realty/create.blade.php
@section('title', 'Добавление Объекта')
@section('section', 'Управление Объектами')
@section('breadcrumbs', Breadcrumbs::render('realty.create'))

<x-app-layout>
    <section class="tile">
        <header class="header-tile">
            <h2><strong>Добавление</strong> Объекта</h2>
        </header>

        {!! Form::open(['route' => 'realty.store', 'class' => 'form body-tile']) !!}
        @include('realty.form', ['realty' => $realty])
        {!! Form::close() !!}
    </section>
</x-app-layout>

resources/views/realty/edit.blade.php
@section('title', 'Редактирование Объекта')
@section('section', 'Управление Объектами')
@section('breadcrumbs', Breadcrumbs::render('realty.edit', $realty))

<x-app-layout>
    <section class="tile">
        <header class="header-tile">
            <h2><strong>Редактирование</strong> Объекта</h2>
        </header>

        {!! Form::model($realty, ['route' => ['realty.update', $realty->id], 'method' => 'PUT', 'class' => 'form body-tile']) !!}
        @include('realty.form', ['realty' => $realty])
        {!! Form::close() !!}
    </section>
</x-app-layout>

resources/views/realty/form.blade.php
<div class="row">
    <div class="col form-item">
        {!! Form::label('account', 'Лицевой Счет:') !!}
        {!! Form::text('account', null, ['class' => 'inp', 'placeholder' => '1234', 'required']) !!}
    </div>
    <div class="col form-item">
        {!! Form::label('type', 'Тип Недвижимости:') !!}
        {!! Form::select('type', \App\Dictionary\RealtyType::TYPES, null, ['class' => 'select', 'required']) !!}
    </div>
</div>

<div class="row">
    <div class="col form-item">
        {!! Form::label('street', 'Улица:') !!}
        {!! Form::text('street', null, ['class' => 'inp', 'placeholder' => 'Зиповская', 'required']) !!}
    </div>
    <div class="col form-item">
        {!! Form::label('house', 'Дом:') !!}
        {!! Form::text('house', null, ['class' => 'inp', 'placeholder' => '36', 'required']) !!}
    </div>
    <div class="col form-item">
        {!! Form::label('flat', 'Квартира:') !!}
        {!! Form::text('flat', null, ['class' => 'inp', 'placeholder' => '56']) !!}
    </div>
</div>

<div class="row">
    <div class="col form-item">
        {!! Form::label('entrance', 'Подъезд:') !!}
        {!! Form::text('entrance', null, ['class' => 'inp', 'placeholder' => '1']) !!}
    </div>
    <div class="col form-item">
        {!! Form::label('floor', 'Этаж:') !!}
        {!! Form::text('floor', null, ['class' => 'inp', 'placeholder' => '12']) !!}
    </div>
    <div class="col form-item">
        {!! Form::label('square', 'Площадь:') !!}
        {!! Form::text('square', null, ['class' => 'inp', 'placeholder' => '56.6']) !!}
    </div>
</div>

<footer class="row footer-tile">
    <a href="{{ URL::previous() }}" class="button light-red">Отмена</a>
    <input type="submit" value="Сохранить" class="button success">
</footer>

resources/views/realty/index.blade.php
@section('title', 'Обзор Объектов')
@section('section', 'Управление Объектами')
@section('breadcrumbs', Breadcrumbs::render('realty.index'))

<x-app-layout>
    <section class="tile">
        <header class="header-tile">
            <h2><strong>Обзор</strong> Объектов</h2>

            <nav class="controls">
                <a href="{!! route('realty.create') !!}"><i class="fa fa-plus"></i> Добавить Объект</a>
            </nav>
        </header>

        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Лицевой Счет</th>
                <th>Тип</th>
                <th>Улица</th>
                <th>Дом</th>
                <th>Квартира</th>
                <th>Дата Создания</th>
                <th>Дата Изменения</th>
                <th class="action-column">Действия</th>
            </tr>
            </thead>
            <tbody>
            @forelse($realtys as $realty)
                <tr>
                    <td>{{ $realty->id }}.</td>
                    <td>{{ $realty->account }}</td>
                    <td>{{ $realty->type_name }}</td>
                    <td>{{ $realty->street }}</td>
                    <td>{{ $realty->house }}</td>
                    <td>{{ $realty->flat }}</td>
                    <td>@datetime($realty->created_at)</td>
                    <td>@datetime($realty->updated_at)</td>
                    <td class="action-column">
                        <a href="{!! route('realty.show', [$realty->id]) !!}" class="button with-icon"
                           data-tooltip="Просмотр"><i class="fa fa-eye"></i></a>
                        <a href="{!! route('realty.edit', [$realty->id]) !!}" class="button with-icon"
                           data-tooltip="Изменить"><i class="fa fa-pencil"></i></a>
                        <a href="javascript:void(0)" class="button with-icon" data-tooltip="Удалить"
                           data-delete="{{ $realty->id }}"><i class="fa fa-trash"></i></a>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="9">
                        <div class="message warning" role="alert">Объекты не найдены!</div>
                    </td>
                </tr>
            @endforelse
            </tbody>
        </table>

        {{ $realtys->links() }}
    </section>
</x-app-layout>

resources/views/realty/show.blade.php
@section('title', 'Просмотр Объекта')
@section('section', 'Управление Объектами')
@section('breadcrumbs', Breadcrumbs::render('realty.show', $realty))

<x-app-layout>
    <section class="tile">
        <header class="header-tile">
            <h2><strong>Просмотр</strong> Объекта</h2>
        </header>

        <article class="body-tile form">
            <div class="row">
                <div class="col form-item">
                    <span class="label">Лицевой Счет:</span>
                    <span class="inp">{{ $realty->account }}</span>
                </div>
                <div class="col form-item">
                    <span class="label">Тип Недвижимости:</span>
                    <span class="inp">{{ $realty->type_name }}</span>
                </div>
            </div>

            <div class="row">
                <div class="col form-item">
                    <span class="label">Улица:</span>
                    <span class="inp">{{ $realty->street }}</span>
                </div>
                <div class="col form-item">
                    <span class="label">Дом:</span>
                    <span class="inp">{{ $realty->house }}</span>
                </div>
                <div class="col form-item">
                    <span class="label">Квартира:</span>
                    <span class="inp">{{ $realty->flat }}</span>
                </div>
            </div>

            <div class="row">
                <div class="col form-item">
                    <span class="label">Подъезд:</span>
                    <span class="inp">{{ $realty->entrance }}</span>
                </div>
                <div class="col form-item">
                    <span class="label">Этаж:</span>
                    <span class="inp">{{ $realty->floor }}</span>
                </div>
                <div class="col form-item">
                    <span class="label">Площадь:</span>
                    <span class="inp">{{ $realty->square }}</span>
                </div>
            </div>

            <div class="row">
                <div class="col form-item">
                    <span class="label">Дата Создания:</span>
                    <span class="inp">{{ $realty->created_at }}</span>
                </div>
                <div class="col form-item">
                    <span class="label">Дата Изменения:</span>
                    <span class="inp">{{ $realty->updated_at }}</span>
                </div>
            </div>

            <footer class="row footer-tile">
                <a href="{{ URL::previous() }}" class="button">Назад</a>
            </footer>
        </article>
    </section>
</x-app-layout>