routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClaimController;
use App\Http\Controllers\RealtyController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ReadingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::resource('client', ClientController::class);

    Route::resource('claim', ClaimController::class);

    Route::resource('realty', RealtyController::class);

    Route::resource('reading', ReadingController::class);
});

require __DIR__.'/auth.php';

app/Models/Client.php
<?php

namespace App\Models;

use App\Traits\Statusable;
use App\Dictionary\ClientRole;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Client extends Model
{
    use HasFactory, Statusable;

    /**
     * @inheritdoc
     */
    protected $fillable = [
        'role', 'first_name', 'last_name', 'middle_name', 'realty_id', 'phone', 'telegram', 'status'
    ];

    /**
     * @return HasMany
     */
    public function claims(): HasMany
    {
        return $this->hasMany(Claim::class);
    }

    /**
     * @return string
     */
    public function getFullNameAttribute(): string
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    /**
     * @return string
     */
    public function getRoleNameAttribute(): string
    {
        return ClientRole::ROLES[$this->role];
    }

    /**
     * @return BelongsTo
     */
    public function realty(): BelongsTo
    {
        return $this->belongsTo(Realty::class);
    }
}

app/Http/Controllers/Api/ClientController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Client;
use Illuminate\Http\Response;
use Illuminate\Http\JsonResponse;
use App\Http\Controllers\Controller;
use App\Http\Requests\Api\StoreClientRequest;

class ClientController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param StoreClientRequest $request
     * @return Response
     */
    public function store(StoreClientRequest $request)
    {
        Client::query()->create($request->validated());

        return response()->noContent();
    }

    /**
     * Display the specified resource.
     *
     * @param Client $client
     * @return JsonResponse
     */
    public function show(Client $client)
    {
        return response()->json($client->toArray());
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Client;
use Illuminate\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use App\Http\Requests\StoreClientRequest;
use App\Http\Requests\UpdateClientRequest;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index()
    {
        return view('client.index', [
            'clients' => Client::query()->paginate()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create()
    {
        return view('client.create', ['client' => new Client()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreClientRequest $request
     * @return RedirectResponse
     */
    public function store(StoreClientRequest $request)
    {
        Client::query()->create($request->validated());

        return redirect()->route('client.index')->with('success', 'Клиент Добавлен!');
    }

    /**
     * Display the specified resource.
     *
     * @param Client $client
     * @return View
     */
    public function show(Client $client)
    {
        return view('client.show', ['client' => $client]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Client $client
     * @return View
     */
    public function edit(Client $client)
    {
        return view('client.edit', ['client' => $client]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateClientRequest $request
     * @param Client              $client
     * @return RedirectResponse
     */
    public function update(UpdateClientRequest $request, Client $client)
    {
        $client->update($request->validated());

        return redirect()->route('client.index')->with('success', 'Клиент Обновлен!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Client $client
     * @return JsonResponse
     */
    public function destroy(Client $client)
    {
        $client->delete();

        return response()->json(['status' => 'success', 'message' => 'Клиент Удален!']);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\View;
use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/client/create.blade.php
@section('title', 'Добавление Клиента')
@section('section', 'Управление Клиентами')
@section('breadcrumbs', Breadcrumbs::render('client.create'))

<x-app-layout>
    <section class="tile">
        <header class="header-tile">
            <h2><strong>Добавление</strong> Клиента</h2>
        </header>

        {!! Form::open(['route' => 'client.store', 'class' => 'form body-tile']) !!}
        @include('client.form', ['client' => $client])
        {!! Form::close() !!}
    </section>
</x-app-layout>

resources/views/client/edit.blade.php
@section('title', 'Редактирование Клиента')
@section('section', 'Управление Клиентами')
@section('breadcrumbs', Breadcrumbs::render('client.edit', $client))

<x-app-layout>
    <section class="tile">
        <header class="header-tile">
            <h2><strong>Редактирование</strong> Клиента</h2>
        </header>

        {!! Form::model($client, ['route' => ['client.update', $client->id], 'method' => 'PUT', 'class' => 'form body-tile']) !!}
        @include('client.form', ['client' => $client])
        {!! Form::close() !!}
    </section>
</x-app-layout>

resources/views/client/form.blade.php
<div class="row">
    <div class="col form-item">
        {!! Form::label('last_name', 'Фамилия:') !!}
        {!! Form::text('last_name', null, ['class' => 'inp', 'placeholder' => 'Иванов', 'required']) !!}
    </div>
    <div class="col form-item">
        {!! Form::label('first_name', 'Имя:') !!}
        {!! Form::text('first_name', null, ['class' => 'inp', 'placeholder' => 'Иван', 'required']) !!}
    </div>
    <div class="col form-item">
        {!! Form::label('middle_name', 'Отчество:') !!}
        {!! Form::text('middle_name', null, ['class' => 'inp', 'placeholder' => 'Иванович']) !!}
    </div>
</div>

<div class="row">
    <div class="col form-item">
        {!! Form::label('realty_id', 'Объект:') !!}
        {!! Form::select('realty_id', \App\Models\Realty::all()->pluck('full_name', 'id')->toArray(), null, ['class' => 'select', 'required']) !!}
    </div>
    <div class="col form-item">
        {!! Form::label('telegram', 'Telegram:') !!}
        {!! Form::text('telegram', null, ['class' => 'inp', 'placeholder' => '3423542342', 'readonly']) !!}
    </div>
    <div class="col form-item">
        {!! Form::label('phone', 'Телефон:') !!}
        {!! Form::tel('phone', null, ['class' => 'inp', 'placeholder' => '79001234567']) !!}
    </div>
</div>

<div class="row">
    <div class="col form-item">
        {!! Form::label('role', 'Роль:') !!}
        {!! Form::select('role', \App\Dictionary\ClientRole::ROLES, null, ['class' => 'select', 'required']) !!}
    </div>
    <div class="col form-item">
        {!! Form::label('status', 'Статус:') !!}
        {!! Form::select('status', $client->statusList(), null, ['class' => 'select', 'required']) !!}
    </div>
</div>

<footer class="row footer-tile">
    <a href="{{ URL::previous() }}" class="button light-red">Отмена</a>
    <input type="submit" value="Сохранить" class="button success">
</footer>

resources/views/client/index.blade.php
@section('title', 'Обзор Клиентов')
@section('section', 'Управление Клиентами')
@section('breadcrumbs', Breadcrumbs::render('client.index'))

<x-app-layout>
    <section class="tile">
        <header class="header-tile">
            <h2><strong>Обзор</strong> Клиентов</h2>

            <nav class="controls">
                <a href="{!! route('client.create') !!}"><i class="fa fa-plus"></i> Добавить Клиента</a>
            </nav>
        </header>

        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Имя</th>
                <th>Фамилия</th>
                <th>Отчество</th>
                <th>Телефон</th>
                <th>Объект</th>
                <th>Роль</th>
                <th class="center">Статус</th>
                <th>Дата Регистрации</th>
                <th class="action-column">Действия</th>
            </tr>
            </thead>
            <tbody>
            @forelse($clients as $client)
                <tr>
                    <td>{{ $client->id }}.</td>
                    <td>{{ $client->first_name }}</td>
                    <td>{{ $client->last_name }}</td>
                    <td>{{ $client->middle_name }}</td>
                    <td>{{ $client->phone }}</td>
                    <td>{{ $client->realty->full_name }}</td>
                    <td>{{ $client->role_name }}</td>
                    <td class="center">{!! $client->status_icon !!}</td>
                    <td>@datetime($client->created_at)</td>
                    <td class="action-column">
                        <a href="{!! route('client.show', [$client->id]) !!}" class="button with-icon"
                           data-tooltip="Просмотр"><i class="fa fa-eye"></i></a>
                        <a href="{!! route('client.edit', [$client->id]) !!}" class="button with-icon"
                           data-tooltip="Изменить"><i class="fa fa-pencil"></i></a>
                        <a href="javascript:void(0)" class="button with-icon" data-tooltip="Удалить"
                           data-delete="{{ $client->id }}"><i class="fa fa-trash"></i></a>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="10">
                        <div class="message warning" role="alert">Клиенты не найдены!</div>
                    </td>
                </tr>
            @endforelse
            </tbody>
        </table>

        {{ $clients->links() }}
    </section>
</x-app-layout>

resources/views/client/show.blade.php
@section('title', 'Просмотр Клиента')
@section('section', 'Управление Клиентами')
@section('breadcrumbs', Breadcrumbs::render('client.show', $client))

<x-app-layout>
    <section class="tile">
        <header class="header-tile">
            <h2><strong>Просмотр</strong> Клиента</h2>
        </header>

        <article class="body-tile form">
            <div class="row">
                <div class="col form-item">
                    <span class="label">Имя:</span>
                    <span class="inp">{{ $client->first_name }}</span>
                </div>
                <div class="col form-item">
                    <span class="label">Фамилия:</span>
                    <span class="inp">{{ $client->last_name }}</span>
                </div>
                <div class="col form-item">
                    <span class="label">Отчество:</span>
                    <span class="inp">{{ $client->middle_name }}</span>
                </div>
            </div>

            <div class="row">
                <div class="col form-item">
                    <span class="label">Telegram:</span>
                    <span class="inp">{{ $client->telegram }}</span>
                </div>
                <div class="col form-item">
                    <span class="label">Телефон:</span>
                    <span class="inp">{{ $client->phone }}</span>
                </div>
            </div>

            <div class="row">
                <div class="col form-item">
                    <span class="label">Роль:</span>
                    <span class="inp">{{ $client->role_name }}</span>
                </div>
                <div class="col form-item">
                    <span class="label">Статус:</span>
                    <span class="inp">{{ $client->status_text }}</span>
                </div>
            </div>

            <div class="row">
                <div class="col form-item">
                    <span class="label">Дата Создания:</span>
                    <span class="inp">{{ $client->created_at }}</span>
                </div>
                <div class="col form-item">
                    <span class="label">Дата Изменения:</span>
                    <span class="inp">{{ $client->updated_at }}</span>
                </div>
            </div>

            <footer class="row footer-tile">
                <a href="{{ URL::previous() }}" class="button">Назад</a>
            </footer>
        </article>
    </section>
</x-app-layout>